[build]
builder = "nixpacks"

[build.nixpacks]
pkgs = ["nodejs_20", "npm-9_x"]

[deploy]
startCommand = "npx prisma generate && npx prisma db push && node prisma/seed.js && node src/index.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

